# Generated by Django 4.1.4 on 2022-12-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_docusign_demo', '0002_auto_20160905_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='signatures', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('sent', 'sent'), ('delivered', 'delivered'), ('completed', 'completed'), ('declined', 'declined')], db_index=True, default='draft', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='signaturetype',
            name='signature_backend_code',
            field=models.CharField(choices=[], db_index=True, max_length=50, verbose_name='signature backend'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('sent', 'sent'), ('delivered', 'delivered'), ('completed', 'completed'), ('declined', 'declined')], db_index=True, default='draft', max_length=50, verbose_name='status'),
        ),
    ]
